from tomcat:9.0.22-jdk13-openjdk-oracle 
COPY target/pratica-spring-mvc-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/pratica.war


# docker image rm pratica-spring-mvc
# mvn clean package
# docker build -t pratica-spring-mvc .
# docker run --rm -p 8080:8080 pratica-spring-mvc