insert into public.advogado(email, nome, oab , telefone) values('seu_email@csjt.jus.br','Usuário do Sistema','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ALINERAITO.AR@GMAIL.COM','ALINE RAITO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fabianoc@terra.com.br','FABIANO MARTINS CAMARGO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('josianipoliti@gmail.com','JOSIANI CONECHONI POLITI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advribeiro@uol.com.br','JOSE RIBEIRO DE CAMPOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jispublic.advogadosassociados@hotmail.com','JOSE ITAMAR DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('av-advocacia@hotmail.com','ADRIANO COSTA AVELINO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dr.gilson@terra.com.br','GILSON MOREIRA DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('debora_turazza@yahoo.com.br','DEBORA NOGUEIRA TURAZZA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('sbarrerto@ftc.br','SUZANA MARIA SANTOS BARRETO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mariahelena-adv@uol.com.br','MARIA HELENA MIRANDA ALVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('pauloafigueiredo@yahoo.com.br','PAULO AFONSO DE FIGUEIREDO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('thaisfernandes.adv@gmail.com','THAIS ESPINDOLA FERNANDES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('clemiltoncarvalho@hotmail.com','CLEMILTON VERAS CARVALHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('flavio.advocacia@terra.com.br','FLAVIO ANTONIO BAPTISTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('judisantos@hotmail.com','JUDIMARA DOS SANTOS MELLO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('joaogamaadv@hotmail.com','JOAO OLIVEIRA GAMA NETO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('samanthachaddad@gmail.com','SAMANTHA CHADDAD DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('filhomauri@hotmail.com','AMAURI DE SOUZA BRITO FILHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('paulaester2014@gmail.com','PAULA ESTER PEREIRA RODRIGUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('allissonristher@hotmail.com','ALLISSON RISTHER SOARES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('felipe.tripode@bpslaw.com.br','CLAUDIO MAURICIO ROBORTELLA BOSCHI PIGATTI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mariana.18arantes@hotmail.com','MARIANA GONZAGA ARANTES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('cristianojs@adv.oabsp.org.br','CRISTIANO DE JESUS DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mvbjones@gmail.com','MARCUS VINICIUS BRAGA JONES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rafael.feltrim@hotmail.com','RAFAEL KAUE FELTRIM OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mauricio@camposveiga.com','MAURICIO DE CAMPOS VEIGA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('vanderlei_vargas@uol.com.br','VANDERLEI PEREIRA VARGAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rodrigodiasabreuadv@gmail.com','RODRIGO DIAS ABREU DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('frantiaiallo39@hotmail.com','FRANTIAIALLO GONCALVES PEREIRA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fabricio@vieiradacunhaadv.com.br','FABRICIO VIEIRA DA CUNHA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('carol_ruette@hotmail.com','CAROLINA LEONE RUETTE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('abilio@cmmpublic.advogados.com.br','ABILIO MACHADO NETO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('manoelw@hotmail.com','MANOEL DE BARROS WANDERLEY NETO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('robert.brito@hotmail.com','ROBERT DA SILVA BRITO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rferraz@sfme.com.br','RAFAELLA FERRAZ SOUZA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ana.jayra@hotmail.com','ANA JAYRA DE SOUSA ALBUQUERQUE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('andressanunesadv@gmail.com','ANDRESSA NUNES DE ALMEIDA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('taycoracao@hotmail.com','TAYANE VIANA DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adv.raimundofilhosobral@hotmail.com','RAIMUNDO FILHO SOBRAL DOS SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ana@covielloetroccoli.com.br','ANA LUIZA TROCCOLI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('karineschuster@yahoo.com.br','KARINE CORREIA COELHO SCHUSTER','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('joao_pacheco-01@hotmail.com','JOAO PEDRO PACHECO CHAVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advocacia.lex@gmail.com','RONI PETER ZANGARI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adv_rauena@hotmail.com','RAUENA CAMPOS DE ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mauricioperecin@gmail.com','MAURICIO MADUREIRA PARA PERECIN','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('raquelsiqueiraa@hotmail.com','RAQUEL SIQUEIRA DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ronepublic.advogado@gmail.com','RONE MUNIZ VIEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('nelsonarraes.adv@gmail.com','NELSON ARRAES FILHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('samuel@cavalcantepereira.adv.br','SAMUEL CUNHA DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dra.silvanialima@gmail.com','SILVANIA LIMA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ian@egsfpublic.advogados.com.br','IAN BARBOSA SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','MICHELLI ELLEN DUARTE VIEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jannadv@hotmail.com','JANNAYNE COSTA PEREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('pollyana.fortaleza@conab.gov.br','POLLYANA MENDES FORTALEZA ALVES CALVO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('cisaescritorio@uol.com.br','JEAN PIERRE DE CAMARGO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fiore.oab@gmail.com','RAPHAEL ALVES FIORE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rosamedauar@hotmail.com','ROSA MEDAUAR OMMATI CHAIB RODRIGUES DE MOURA SANTOS CORDEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rflpublic.advogados@terra.com.br','RENATO FERREIRA DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('draedna@com4.com.br','EDNA GOMES BRANQUINHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('EDUMAJARAO@HOTMAIL.COM','EDUARDO SILVEIRA MAJARAO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('kaiomikaelsampaio@gmail.com','KAIO MIKAEL DA COSTA SAMPAIO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('olecramdosanjos@hotmail.com','MARCELO ALVES DOS ANJOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('faelns@hotmail.com','RAFAEL NASCIMENTO DOS SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('asf.advocacia@hotmail.com','ALEXANDRE SARGE FIGUEIREDO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gabriel@cavalcantepereira.adv.br','GABRIEL PEREIRA DE CARVALHO CRUZ','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('olimpio@adcg.adv.br','OLIMPIO CARNEIRO DA SILVA FILHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('flavio@bbaadv.com','FLAVIO AUGUSTO ALVERNI DE ABREU','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','JOANA DARC CAVALCANTE NASCIMENTO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('maxjuridico@hotmail.com','THIAGO ROBERTO MORAIS DIAZ','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('daviquintiliano@hotmail.com','DAVI QUINTILIANO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gislenebsl@yahoo.com.br','GISLENE BATISTA SANTOS LIMA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('prisaiastorres@gmail.com','ISAIAS TORRES SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('joseairton.m@hotmail.com','JOSE AIRTON MARQUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','LARISSA MOTA DE ALENCAR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luis_henriquegomes@hotmail.com','LUIS HENRIQUE DE ALMEIDA GOMES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('salvadorrodrigues@jhsf.com.br','COMPANHIA METRO NORTE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('manfrim.adv@ig.com.br','JUAREZ MANFRIN FILHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gizafigueredo@yahoo.com.br','GIZELLE FIGUEREDO DE CARVALHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gmbsantos@aasp.org.br','GERALDO MAJELA BALDACIN DOS SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('anamercia@ambpublic.advogados.com.br','ANA MERCIA AZEVEDO NASCIMENTO SANTA BARBARA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marianacgn@hotmail.com','MARIANA COELHO GOMES NOBREGA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('maat_10001@hotmail.com','VITORIO NEIVA DE ALENCAR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('conchita@marcondescesar.adv.br','CONCHITA OLIVEIRA SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('w4ll1s0n@hotmaill.com','WALLYSON WENDELL SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('cristiane@morgadopublic.advogados.com.br','CRISTIANE MORGADO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('brunofiliperochadasilva@hotmail.com','BRUNO FILIPE ROCHA DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('alexandrebmaia@globo.com','JOSE ALEXANDRE BEZERRA MAIA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('castroepires@adv.oabsp.org.br','GILBERTO MARQUES PIRES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','LISIANE GOMES DE SOUZA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('santuccidias@adv.oabsp.org.br','PAULO VITOR SANTUCCI DIAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('raquel@outlook.com.br','RAQUEL DUTRA MARTINS ASSUNCAO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jmraffaelli@terra.com.br','JOAO MIGUEL RAFFAELLI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('tcrispagliusi@hotmail.com','LUIZA PAGLIUSI DAMIANO CAVICCHIOLI DE CASTRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adaoaraujoadv@hotmail.com','ADAO ARAUJO DE SOUZA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('torres@colegioteresopolitano.com.br','FRANCISCO DE ASSIS RODRIGUES TORRES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('pri_rochaphb@hotmail.com','PRISCILA DA SILVA ROCHA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('benavent@aasp.org.br','JOSE ANTONIO BENAVENT CALDAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('pedroaug79@gmail.com','PEDRO AUGUSTO DE ARAUJO MARQUES BARBOSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gcostanunes@ig.com.br','GENESIO DA COSTA NUNES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('julianamotta@mepublic.advogados.com.br','JULIANA DA MOTTA BERGLER','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rogerio.goncalves@gsantos.adv.br','ROGERIO LOVIZETTO GONCALVES LEITE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('souza-lucas@hotmail.com','LUCAS SOUZA PEREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('laiscarruda.adv@hotmail.com','LAIS ELLEN DE CARVALHO ARRUDA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('aldemarjrj@gmail.com','ALDEMAR SOARES LIMA JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('perusso.public.advogados@terra.com.br','CAROLINE PERUSSO GOLDANI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('joao@castelobrancoenapoleao.com','JOAO NETO PINHEIRO NAPOLEAO BRAZ','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('EDSONPSF@HOTMAIL.COM','EDSON PINTO DA SILVEIRA FILHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('izabelcarmo.adv@gmail.com','IZABEL PEREIRA DO CARMO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adv.paulobruno@gmail.com','PAULO BRUNO RODRIGUES DOMINGOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adv.anachirles@hotmail.com','ANA CHIRLES DE SOUSA NETA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('clauzer@pinheirofernandes.adv.br','CLAUZER MENDES CASTRO PINHEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('maltapublic.advogados@hotmail.com','MARCIA VIEIRA DE MELO MALTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jdpiresadv@hotmail.com','JOSE DONIZETI PIRES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('joaomabcmonteiro@adv.oabmg.org.br','JOAO MARCOS ALENCAR BARROS COSTA MONTEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advsimonecamargo@gmail.com','SIMONE CAMARGO DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fvds36@hotmail.com','FERNANDA VESPASIANO DE SA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marilenejaicos@hotmail.com','MARILENE DE OLIVEIRA VERA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','FELIPE LEAL SOUZA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('diligencias@capistranocarvalho.com','FRANCISCA DAS CHAGAS ARAUJO CARVALHO CAPISTRANO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marcusripoli@bol.com.br','MARCUS RUBENS SIVIERO RIPOLI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('juslog07@juslog.com.br','BARBARA BARROS BOTEGA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('carloslima.adv3@hotmail.com','CARLOS LIMA DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('raimundons06@hotmail.com','RAIMUNDO NONATO DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adv.zagattialves@yahoo.com.br','RAFAEL ZAGATTI ALVES PEREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rodrigo_martins_mat@hotmail.com','RODRIGO MARTINS MATSUMOTO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('bianca.ferraz@mafraadv.com.br','BIANCA FERRAZ BARROSO ALBUQUERQUE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('leandrofadel@hotmail.com','LEANDRO FADEL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('eduardo.dutra@benicio.com.br','EDUARDO DIAS DUTRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fabrinascunha@hotmail.com','FABRINA SOARES DA CUNHA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('soaresrocha.rogerio@gmail.com','ROGERIO SOARES DA ROCHA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('andre@schwerzpublic.advogados.com.br','ANDRE LUIZ RAMOS DE CAMARGO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('cavourcaldas@gmail.com','CAVOUR CALDAS JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('alexandrechagasbv@hotmail.com','FRANCISCO ALEXANDRE DAS CHAGAS SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luzi-aaa@hotmail.com','MARIA LUZIA ALVES ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lubmagalhaes@hotmail.com','LUCIANO BOMFIM MAGALHAES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luizfagundesjurista@gmail.com','LUIZ FERNANDO DA SILVA FAGUNDES MARQUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('diogo.pires@trt1.jus.br','DIOGO PIRES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('kiiler.vania@uol.com.br','VANIA CARLA KIILER','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marcielbarrosadv@yahoo.com','MARCIEL BARROS DE ALCANTARA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('edirene.juridico@patrimonioweb.com.br','EDIRENE DOS SANTOS MARINHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rosana.galvao24@hotmail.com','ROSANA GALVAO CABRAL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('janainasilval@hotmail.com','JANAINA SILVA LIMA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('blcmt@terra.com.br','CELSO PIZANESCHI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('isaacdiego1@gmail.com','ISAAC DIEGO MELO DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('vagnernunesfh@yahoo.com.br','JOSE VAGNER FONSECA NUNES FILHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dricristini@yahoo.com.br','ADRIANE CRISTINI DE PAULA ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('geisedecarvalho5@gmail.com','GEISE DE CARVALHO SOUSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('andchoal@ig.com.br','ANDRE LUIZ PASCHOAL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','ANA ELIZA RAMOS SANDOVAL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advjlo@yahoo.com.br','JOILSON LUIZ DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rebecamartins.adv@gmail.com','REBECA DE AGUIAR MARTINS RODRIGUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advsac@gmail.com','SANDRO ANDRE COPCINSKI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('sousa033@hotmail.com','MARIA NUBIA DOS SANTOS SOUSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('douglasfrancotorres@hotmail.com','DOUGLAS FRANCO TORRES DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('costa.cristina@uol.com.br','CRISTINA DO NASCIMENTO COSTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('glmota@yahoo.com.br','ANTONIO GLAUCO FONSECA MOTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('camila.coroa@hotmail.com','CAMILA ALVES COROA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fernanda.barretta@uol.com.br','FERNANDA BARRETTA GUIMARAES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('perseumello@hotmail.com','PERSEU MELLO DE SA CRUZ','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('iberejofili2@hotmail.com','IBERE JOFILI LOPES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('carolinaneddermeyer@ribeirocoelho.com.br','CAROLINA NEDDERMEYER VON PARASKI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('arthur.flima06@gmail.com','ARTHUR FAUSTINO FERREIRA DE LIMA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('danielelilian@hotmail.com','LILIAN DANIELLE NASCIMENTO DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('alvanycardoso@gmail.com','ALVANY DA SILVA CARDOSO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('evandrohildebrand@gmail.com','EVANDRO BEZERRA DE MENEZES HILDEBRAND','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('forchesatto@yahoo.com.br','EDUARDO LUIS FORCHESATTO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('thiagovasques@gmail.com','THIAGO CORREA VASQUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('email@dpu.gov.br','DEFENSORIA PUBLICA DA UNIAO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('leonardo.vitorino@caixa.gov.br','LEONARDO GUILHERME DE ABREU VITORINO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lfgoncalves@aasp.org.br','LUIZ FERNANDO GONCALVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('romulogb@bnb.gov.br','ROMULO GONCALVES BITTENCOURT','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rafael.reis@clr.com.br','RAFAEL BORTONE REIS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rodrigoferreira@equipetributaria.com.br','RODRIGO FERREIRA DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('munir_bossoe@hotmail.com','MUNIR BOSSOE FLORES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('raizacarvalhoo@hotmail.com','RAIZA CAROLINE CARVALHO ROCHA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('is-public.advogados@uol.com.br','IVAN DE CASTRO PAULA JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('debora@advgr.com.br','DEBORA GABANYI RAYS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('theoramorim@gmail.com','THEOPHYLO ROCHA DE AMORIM','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('aturella.adv@gmail.com','ARIANE DOS SANTOS TURELLA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advocacia.fvs@hotmail.com','FERNANDA VASCONCELLOS DE SANTANA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dcmelhado@gmail.com','DINORAH CRISTINA MELHADO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('alice@hilkneraltieri.com.br','ALICE XAVIER DE CARVALHO MARQUES ALLEGRETTI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('anaruth_sj@hotmail.com','ANA RUTH BATISTA DE FREITAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('berrios@terra.com.br','MARCELO ANDRES BERRIOS PRADO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('tneto@globo.com','TANCREDO CASTELO BRANCO NETO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('markcf_2004@hotmail.com','MARCOS CESAR DE FARIA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jose.soares@mpt.gov.br','JOSE WELLINGTON DE CARVALHO SOARES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rodrigo.ribeiroadv@hotmail.com','RODRIGO JOSE RIBEIRO SOUSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rfm@gh.adv.br','ROBERTO DE FARIA MIRANDA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('samantha@martinspossas.com.br','SAMANTHA IAMEE SILVA DE MORAIS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('milenadipierro@hotmail.com','MILENA BASSANI DE SANTANA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('assisnunes2@bol.com.br','FRANCISCO DE ASSIS GOMES NUNES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adv.sabrinacosta@gmail.com','SABRINA RAFAELA FREITAS COSTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gimenezpublic.advogados1@gmail.com','VANESSA GIMENEZ','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('miura.advocacia@terra.com.br','JULIA ARAUJO MIURA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rodrigo@adcg.adv.br','RODRIGO LEAL CANTARELLI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ronnysanny@yahoo.com.br','RONNY SANNY DA SILVA LOPES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ernandacalado@hotmail.com','ERNANDA MAURICIO CALADO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('leo-advg@hotmail.com','LEONARDO DE LIMA RAMOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fernando.rossi@netsite.com.br','FERNANDO FONSECA ROSSI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jabreu@eapublic.advogados.com.br','JOSE ANTONIO ALVES DE ABREU','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marcelo.dezem@dezemrodrigues.com.br','MARCELO DEZEM DE AZEVEDO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('drclaudima@hotmail.com','CLAUDIO RODRIGUES LIMA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advprevjus@hotmail.com','EMANUEL NAZARENO PEREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mrejaneangelo@hotmail.com','MARIA REJANE OLIVEIRA ANGELO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('isaac.abrantes@hotmail.com','ISAAC ABRANTES FERNANDES CAVALCANTI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('emerson@castroneves.com.br','EMERSON MARTINS REGIOLLI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ricardo_russo@ig.com.br','RICARDO ANTONIO SOARES RUSSO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('sergio.r.contri@gmail.com','SERGIO LUIZ RIBEIRO CONTRI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dr.marcosoliveirapi@gmail.com','MARCOS VINICIUS DO AMARAL OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('drcassioxavier@gmail.com','CASSIO GARCIA XAVIER','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('samuelcastelobranco@ig.com.br','SAMUEL CASTELO BRANCO SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('kelly.santana@schmideleassociados.com','ALAN VAGNER SCHMIDEL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('thiagoalmeidanascimento@yahoo.com.br','THIAGO ALMEIDA NASCIMENTO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('herbeth.adv@hotmail.com','HERBETH ARAUJO DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('daniele@orgunidas.com.br','DANIELE DE ALMEIDA MARTINS COSTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('janaina@toledoadvocacia.com','JANAINA CLAUDIA DE MAGALHAES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luanaregina@hotmail.com','LUANA REGINA RIBEIRO DA FONSECA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('cinthya.mesquita1@gmail.com','CINTHYA CHRISTINA ZEFERINO MESQUITA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('pinheirojus@outlook.com','DANILO PINHEIRO SOUSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('aeltonmauriz@hotmail.com','AELTON BORGES MAURIZ','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jose.tomaz@pvspublic.advogados.com','JOSE TOMAZ DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('raes@faltapensar.com.br','RAMIRO CUSTODIO DE SOUZA JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fagundes_adv@yahoo.com.br','JOSE LUIZ PAIVA FAGUNDES JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('renatocs366@gmail.com','RENATO COSTA SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jh_bb@hotmail.com','JOAO HENRIQUE BATISTA BARROS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advborba@hotlink.com.br','FERNANDO ANTONIO DA COSTA BORBA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('filipe@fialdini.com.br','FILIPE SCHMIDT SARMENTO FIALDINI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lucianomonteiro.adv@hotmail.com','LUCIANO MONTEIRO DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ricardocernew@yahoo.com.br','RICARDO CERNEW','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('MTApublic.advogado@HOTMAIL.COM','MILTON TADEU DE ALMEIDA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('aline.mattiazzo@gmail.com','ALINE POSSETTI MATTIAZZO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jucianomonte@hotmail.com','JUCIANO MARCOS DA CUNHA MONTE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('thaynarariedel@hotmail.com','THAYNARA MARWELL DE OLIVEIRA RIEDEL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('andersonribasmiranda@hotmail.com','ANDERSON SARAIVA LEITE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gustavo@martinspossas.com.br','GUSTAVO PINTO COELHO VIMIEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lukfsoares@gmail.com','LUCA FRANCA DA COSTA SOARES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luciano_pimenta@aasp.org.br','LUCIANO PIMENTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('passosviviane6@gmail.com','VIVIANE PASSOS DA COSTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('liarabelo@live.com','LIA RAQUEL SOUSA RABELO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('larissabraga_9079@hotmail.com','LARISSA BRAGA SOARES DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('sergio@barretosantos.adv.br','SERGIO BARRETO DOS SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('heliokleves_9@hotmail.com','HELIO KLEVES RIBEIRO OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('aacavalcanti86@hotmail.com','ANDRE DASSUMPCAO CAVALCANTI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('caltabianoescritorio@hotmail.com','EDSON MIRANDA CALTABIANO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('carla@moisesreis.com.br','CARLA FERNANDA DE OLIVEIRA REIS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('wm-advocacia@hotmail.com','WELDER DE SOUSA MELO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('anacristina@eliasrodrigues.adv.br','ANA CRISTINA DA COSTA ELIAS OLIVARI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gomesealves@hotmail.com','FERNANDA GOMES ALVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('MARCIA@CASTRONEVES.COM.BR','MARCIA MENDES DE FREITAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('augustonunes_1@hotmail.com','AUGUSTO JOSE DE MEDEIROS NUNES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('victoriacuryc@gmail.com','VICTORIA SARABANDO CURY CORDEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('hamilton.ayres@hotmail.com','HAMILTON AYRES MENDES LIMA JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('weltton@bnb.gov.br','WELTTON RODRIGUES LOIOLA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('loana.mendonca@serpro.gov.br','LOANA MEDEIROS SILVA MENDONCA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('paulo@caretapublic.advogados.com.br','PAULO DE TARSO CARETA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('af@briganti.com.br','ALEXANDRE FRAGOSO SILVESTRE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('tascila_assessorize@hotmail.com','TASCILA TELES FERREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('endersonlimaadv@gmail.com','ENDERSON FLAVIO COSTA LIMA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('estrella@mauespublic.advogados.com.br','RODRIGO MAIA RIBEIRO ESTRELLA ROLDAN','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('cmfortess@gmail.com','CAROLINA MACHADO FORTES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lanaraferreiracampos@hotmail.com','LANARA FERREIRA CAMPOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('renatamonteiroadv@hotmail.com','RENATA DE ALMEIDA MONTEIRO ALVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('joaocarlosescritorio@gmail.com','JOAO CARLOS FERREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('forneladvocacia@adv.oabsp.org.br','JOAO DIOGENES FORNEL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('carlos.public.advogado@bol.com.br','CARLOS FRANCISCO MACHADO DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('camposribeiro.adv@gmail.com','LUCIANA ALVES RIBEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mariliagtr@gmail.com','MARILIA GONDIM TORRES DA ROCHA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mary.boralli@hotmail.com','MARISA BARBIERI BORALLI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gabrielreis@gmail.com','GABRIEL FREDERICO CESAR DOS REIS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('daianemadureira@adv.oabsp.org.br','DAIANE DA SILVA MADUREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('alex.s.dias@uol.com.br','ALEXANDRE DOS SANTOS DIAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ursulalyrio1@yahoo.com.br','URSULA LYRIO DO VALLE SIQUEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('aluysioricardo@yahoo.fr','ALUYSIO RICARDO NUNES FONSECA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('nagyb@jwis.adv.br','NAGYB BEZERRA BARBALHO VIEIRA DANTAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('haroldo@almendroecarnevale.adv.br','HAROLDO DEL REI ALMENDRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advnegreirosemoura@hotmail.com','LORENA MARTINS VIEIRA PIRES DE MOURA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('shirley@vetec.com.br','SHIRLEY MERY MARIN','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ricardogf@trt22.jus.br','RICARDO GOMES FERREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marcadvocacia@bol.com.br','MIGUEL ARCANJO SILVA COSTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('elton.jg@gmail.com','ELTON DE JESUS GONCALVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('thatianamoraesadv@gmail.com','THATIANA AARAO DE MORAES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('RFCOSTA@AASP.ORG.BR','ROSINEIDE FERNANDES DA COSTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('estelaknitter@gmail.com','ESTELA KNITTER BARROS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luvelozo@hotmail.com','LUCIANA FATIMA FERNANDES VELOZO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('MORGANAMORAIS@QUEIROZCAVALCANTI.ADV.BR','MORGANA FIGUEIREDO MORAIS REIS NOGUEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fdaporto@gmail.com.br','RAFAEL FERRAREZI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('matheusbonaroti@hotmail.com','MATHEUS BONAROTI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('emerpom@globo.com','EMERSON POMPEO CARCARA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rosevan@martiniadv.com.br','ROSEVAN DO NASCIMENTO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('eduardosindo@hotmail.com','EDUARDO MARQUES FONSECA SINDO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gtanaca@zopone.com.br','GUSTAVO TANACA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('deonisiodf@globo.com','DEONISIO DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adv.camilamesquita@gmail.com','CAMILA MESQUITA BARBOSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('arnoldonuneslima@gmail.com','ARNOLDO NUNES DE LIMA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rpngarcia@uol.com.br','RONAN PINHO NUNES GARCIA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('miguelvillegas@uol.com.br','MIGUEL COUTO DORNEL VILLEGAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ma_cappelin@hotmail.com','MARIANA CAPPELIN DO AMARAL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('alessandra.francisco@mmaalaw.com','ALESSANDRA FRANCISCO DE MELO FRANCO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jad23public.advogado@gmailcom','JORGE ALBERTO DIAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('cibelemangine@hotmail.com','CIBELE CRISTINA MANGINI CORREA REIS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('nayracf@hotmail.com','NAYRA CONCEICAO FERNANDES DE ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('angelaavelinoadv@gmail.com','ANGELA ALESSANDRA AVELINO E SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('pcongiu@gmail.com','PATRICIA DA CUNHA CONGIU','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('viniciusmontenegro@tostesdepaula.adv.br','VINICIUS FERREIRA FARIAS MONTENEGRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('petruciovanderlei@terra.com.br','PETRUCIO ROMEU LEITE VANDERLEI JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('guzmore1@hotmail.com','CARLOS GUSTAVO COSTA DE SOUSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('caiomartinsreis@gmail.com','CAIO MARTINS REIS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('paulobland@gmail.com','PAULO HENRIQUE VIEIRA DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('danielsapereira@hotmail.com','DANIEL DACIER LOBATO SA PEREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('armotapublic.advogados@gmail.com','ANTONIO ERLANDE SILVA MOTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dhiegoberg@gmail.com','DHIEGO BERG ARAUJO DE ALMEIDA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('eduardomourarochaesilva@yahoo.com.br','EDUARDO MOURA ROCHA E SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('leidecostaadvsp@outlook.com','LEIDE PEREIRA DA COSTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('wesley.carneiro1@gmail.com','WESLEY CARNEIRO DE ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('danielpassosdebritoadv@gmail.com','DANIEL PASSOS DE BRITO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('srvillares@uol.com.br','SANDRA RODRIGUES DA SILVA VILLARES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('anapatriciajq@hotmail.com','ANA PATRICIA JANJA QUEZADO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('geralddonetto@hotmail.com','GERALDO BORGES LEAL NETO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('zamabarujo@yahoo.com.br','ROBERTO SANTOS ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rubensmenezesadvocacia@gmail.com','RUBENS DE SOUSA MENEZES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('anb@martorelli.com.br','ANNAMELIA MENDES BRANDAO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lorenaramos@hotmail.com.br','LORENA RAMOS RIBEIRO GONCALVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gersonleao-@hotmail.com','GERSON LEAO NUNES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marcosfq@oi.com.br','MARCOS FIRMINO DE QUEIROZ','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mauriciojradv@yahoo.com.br','MAURICIO DE MORAIS MACHADO JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('filipoovick@gmail.com','IVAN THIAGO FALCAO RODRIGUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('antonio.viana.sousa@bol.com.br','ANTONIO CARLOS VIANA DE SOUSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rafaelap@aer.adv.br','RAFAELA POSSERA RODRIGUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('af.mesquita@adv.oabrj.org.br','ANDREIA FRANCISCA DE MESQUITA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('matheusreseda@gmail.com','MATHEUS RICCIO RESEDA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jr.rsousa@hotmail.com','FRANCISCO RODRIGUES DE SOUSA JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('robertosantosadv@gmail.com','ROBERTO SANTOS DE JESUS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('cmoruzzi@hotmail.com','CAETANO MARCONDES MACHADO MORUZZI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('washingtonnascimentopublic.advogado@gmail.com','FRANCISCO WASHINGTON DO NASCIMENTO SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('juridico@lwart.com.br','DENISE GOMES DE SANTANA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('felipe_rios@cevasa.com.br','FELIPE ROCES RIOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('antoniomarcos@fontesassessoria.com.br','ANTONIO MARCOS BARBOSA FONTES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('pedro_vilarinho10@hotmail.com','PEDRO ALBERTO DA SILVA NETO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marciodias@msdpublic.advogados.com.br','MARCIO ROGERIO DOS SANTOS DIAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marcio@fernandesdonas.com.br','MARCIO MACHADO VIEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('abraao@estol.adv.br','ABRAAO SOARES DOS SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advocaciamroliveira@hotmail.com','MAURICEIA RAMOS DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('josueneves80@yahoo.com.br','JOSUE SILVA NEVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gustavoadv@hotmail.com','GUSTAVO RIBEIRO PINTO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fvianna@aasp.org.br','FABIO EMPKE VIANNA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('vitor.rego@hotmail.com.br','VITOR REGO DE AMORIM','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('controladoria2@bsapublic.advogados.com.br','LUCIANA SBRISSIA E SILVA BEGA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('alineborja@hapvida.com.br','ALINE CARVALHO BORJA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gabriellymorgana@hotmail.com','GABRIELLY MORGANA ELLEN DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('robcor@uol.com.br','ROBERTO CORDEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('anabela@galvaoassociados.com.br','ANABELA GALVAO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('simonegelinski@yahoo.com.br','SIMONE MARINA GELINSKI BRANDL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('aquiles-oliveira@brturbo.com.br','AQUILES RODRIGUES DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luanapeixotoo@yahoo.com.br','LUANA PEIXOTO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('paulo.freitas@freitasmartinho.adv.br','PAULO HENRIQUE DE SOUZA FREITAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('helioluciof@hotmail.com','JOSE HELIO LUCIO DA SILVA FILHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('yan.dias10@hotmail.com','YAN PAULA PESSOA DIAS ANDRADE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('symone-lima@hotmail.com','SIMONE LIMA CAVALCANTE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mayraperesadv@hotmail.com','MAYRA LEANNE PEREIRA PERES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('amilcarfjjunior@gmail.com','AMILCAR FERREIRA JAIME JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mauricio.christino@aasp.org.br','MAURICIO SERGIO CHRISTINO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('claudio@hiratapublic.advogados.com.br','CLAUDIO HIRATA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advfranciscooliveira@hotmail.com','FRANCISCO SOARES DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('moises@mecconsultoria.com','MOISES DOS SANTOS GOMES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('josemurilo@sfcs.adv.br','JOSE MURILO LYRA ARRUDA DE ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('felipetsilva22@hotmail.com','FELIPE TEODORO DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('milcalouis@gmail.com','MILCA JOANA DE OLIVEIRA PINTO DE MESQUITA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('glaucocampelo_adv@hotmail.com','GLAUCO DJAFAR DE OLIVEIRA CAMPELO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('grespan@grespan.adv.br','MARCO AURELIO GRESPAN','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('natyfreitas_sfs@hotmail.com','NATALIA SILVA DE FREITAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('juliana.grama@aasp.org.br','JULIANA GRAMA PRADO DE CARVALHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('deborahcabral67@gmail.com','DEBORAH CABRAL SIQUEIRA DE SOUZA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('paulinha.tepedino@hotmail.com','PAULA LOPES TEPEDINO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marcio2003rj@yahoo.com.br','MARCIO JOSE LISBOA FORTES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('elanolima@hotmail.com','ELANO LIMA MENDES E SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('oseiasadv@hotmail.com','OSEIAS NASCIMENTO DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('wilsonjfneto@hotmail.com','WILSON JOSE FERREIRA NETO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('joseninosousa007@hotmail.com','JOSENINO COSTA SOUSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('moniquemason2010@hotmail.com','MONICA MONIQUE MASON','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('cwenderson@hotmail.com','CARLOS WENDERSON REGO VASCONCELOS SINIMBU','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lnradv@gmail.com','LAECIO NOGUEIRA REBOUCAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('paulorogerio@teixeiraadvogacia.com.br','PAULO ROGERIO TEIXEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('byancacorrea@superig.com.br','BIANCA APARECIDA DE CAMPOS CORREA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('moraesbarros@hotmail.com','SERGIO LUIZ DE MORAES BARROS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rcardoso@sfme.com.br','ROMULO CARDOSO ARRUDA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lucas.schich@gmail.com','LUCAS SCHICH VARGER ABRANTES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lmornellas@hotmail.com','LAURA MARIA ORNELLAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('deciojr70@hotmail.com','DECIO ATTOLINI JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lucascprevatto@hotmail.com','LUCAS CUNHA PREVATTO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('eliamcardoso@yahoo.com.br','ELIANA MARCIA GONCALVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('raquelcoutoterra@gmail.com','RAQUEL COUTO TERRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('tatiana-morais1@hotmail.com','TATIANA DE MORAIS ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('glucas.carneiro@yahoo.com.br','GEORGE LUCAS BEZERRA CARNEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('aureanesilva@hotmail.com','AUREANE RODRIGUES DA SILVA PINESE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('aldair.rios@hotmail.com','ALDAIR RAMOS RIOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('carloscesarmb@yahoo.com.br','CARLOS CESAR MENDES BATISTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('isoldaspereira@yahoo.com.br','ISOLDA SILVA PEREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('leonardomenezes.adv@gmail.com','LEONARDO MAJE DE MENEZES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('tatianeboliveira.adv@gmail.com','TATIANE BARBOSA DE OLIVEIRA DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('kaio_botelho@hotmail.com','KAIO PINHEIRO BOTELHO COSTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('advlindemberg@gmail.com','LINDEMBERG DOS SANTOS SEVERO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('geraldofff@gmail.com','GERALDO FORTES FREITAS FILHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lilian.advocacia@hotmail.com','LILIAN ERICA LIMA RIBEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dra.helianicy@gmail.com','HELIANICY DA CONCEICAO VIEIRA SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('sergioadvleite@gmail.com','SERGIO AUGUSTO DA SILVA LEITE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','ANDREA GONÇALVES DE MOURA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('xeniafukuji@siqueiracastro.com.br','XENIA VARGAS PATROCINIO FUKUJI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('doni_direito@yahoo.com.br','JOSE DONIZETI DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fscadm@yahoo.com.br','FABIANO SALES CONTENTE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('alexrtr@hotmail.com','ALEX REIS TRINDADE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('mcbf@aasp.org.br','MARIA CECILIA BARBANTE FRANZE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('bruna@fcarneiroadv.com.br','BRUNA MELO CARNEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fernando@advocaciastein.com.br','FERNANDO SILVA DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('liarmonteiro@hotmail.com','LIA RODRIGUES MONTEIRO DE MELO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fabiana.vitorio@pppadv.com.br','FABIANA VITORIO BIANCO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ana_van@terra.com.br','ANA VANESSA FELIPE BEZERRA PEREIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('carlosdavi_321@hotmail.com','CARLOS DAVI MARTINS MARQUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('joanao482@gmail.com','JOANA OLIVEIRA SOUSA PINTO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','KENNEDY REIAL LINHARES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('daniellebellina@scbpublic.advogados.adv.br','DANIELLE DE ABREU BELLINA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('atillacosta.adv@outlook.com','ALLEX ATILLA COSTA DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('tomebastiao@yahoo.com.br','JOAO EUDES RAMOS JUNIOR','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('brudan@terra.com.br','DANILO MENDES MIRANDA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('elildes@fortalezasantos.com.br','ELILDES FORTALEZA SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fernandadecastrogomes@hotmail.com','FERNANDA DE CASTRO GOMES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('heldirmacedoadv@hotmail.com','HELDIR MACEDO AZEVEDO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('oliveira.elionai@gmail.com','ELIONAI GONCALVES DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dragracielemonteiro@hotmail.com','GRACIELE DO NASCIMENTO MONTEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dr.elimaciel@terra.com.br','ELI MACIEL DE LIMA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('dayanamoura.adv@gmail.com','DAYANA RAMOS SANTANA MOURA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('email@dnocs.gov.br','DEPARTAMENTO NACIONAL DE OBRAS CONTRA AS SECAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marinnetupinambaadv@outlook.com','MARINNE AUGUSTA DE ALMEIDA MOITA TUPINAMBA RODRIGUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rhavenacabral@hotmail.com','ANA RHAVENA COSTA CABRAL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('daniel@cpdppublic.advogados.com.br','DANIEL GRANA ZORZETE','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marcosugf@hotmail.com','MARCOS FERREIRA DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','MARCUS VINICIUS CHAVES OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lacordai@gmail.com','LACORDAIRE GUIMARAES DE OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lmarques@machadomeyer.com.br','LIGIA FERNANDES MARQUES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('emilia.lacerda@itabaiana.adv.br','MARIA EMILIA MANDARIM DE LACERDA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('julibarbosa@gmail.com','JULIANA BARBOSA GUEDES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rustene.rocha@hotmail.com','RUSTENE ROCHA MONTEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('larissa@atn.adv.br','LARISSA NUNES REGIS OLIVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marcia@trt22.jus.br','MARCIA FERNANDA LEAL VELOSO CAVALCANTI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('josuedias.sousa@hotmail.com','JOSUE DIAS DE SOUSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adv.sergioviana@hotmail.com','SERGIO FERREIRA VIANA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('apessoa@klalaw.com.br','ALEXANDRE PESSOA AFONSO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','GUSTAVO LUIZ LOIOLA MENDES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rodrigo.x.s@hotmail.com','RODRIGO XAVIER SOARES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('eduardomarcell21@hotmail.com','EDUARDO MARCELL DE BARROS ALVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('wan.castro@hotmail.com','WANDERSON CASTRO SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('juridico@altamogiana.com.br','LEONARDO BRUNO LOPES DE ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('souza_neia@yahoo.com.br','JOCINEIA SOUZA DE JESUS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marco_herrero@invivo-nsa.com.br','MARCO ANTONIO PRADO HERRERO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('gustavobayerl.intimacoes@gmail.com','GUSTAVO BAYERL LIMA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('monicacerqueiraadv@hotmail.com','MONICA MARIA FRAZAO BRITO CERQUEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ffsantos.2006@hotmail.com','FRED FARIAS DOS SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('victormachado-adv@bol.com.br','VICTOR AUGUSTO MACHADO DE SOUZA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('clarice_omc@hotmail.com','CLARICE OLIVEIRA MARTINS DA COSTA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('flaviage@gmail.com','FLAVIA ALEXSANDRA NOLETO DE MIRANDA CARVALHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('theo.benini@gmail.com','THEO BENINI DE GODOY','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('pri.silva200@hotmail.com','PRISCILA JOQUEBEDDE E SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','VANESSA NUNES DE BARROS MENDES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jamile.machado@trt22.jus.br','JAMILE SILVA MACHADO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('sabaini@sabaini.com.br','ANTONIO ELSON SABAINI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('public.advogadopablo@gmail.com','PABLO RICARDO VARGAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('alessandrama@odebrecht.com','ALESSANDRA DE ANDRADE BARBOSA SANTOS DE MESQUITA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('leviterceiro@gmail.com','LEVI MARTINS DE MELO TERCEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adriano@rebellopublic.advogados.com.br','ADRIANO MUNIZ REBELLO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('','JOELICA JORIA CARVALHO DE ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ricardo.pereira@adv.oabsp.org.br','RICARDO PEREIRA DA SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ivana.leal@agu.gov.br','IVANA DE SOUSA LEAL','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('tamyresaragao@hotmail.com','TAMYRES ARAGAO MASCARENHAS RIBEIRO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fa.a.s@adv.oabmg.org.br','FABIANO ALVES DOS SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('pedro_artuzo@hotmail.com','PEDRO HENRIQUE ARTUZO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('rossanapimentelsantos@hotmail.com','ROSSANA CARVALHO PIMENTEL DOS SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('thiagoceara@hotmail.com','THIAGO IBIAPINA PORTELA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('brauliocronemberger@hotmail.com','BRAULIO GIANNINI COELHO CRONEMBERGER','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('tiagomelo93@live.com','TIAGO MELO GONCALVES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('adv.brunaleticia@gmail.com','BRUNA LETICIA MARGARIDA DOS SANTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lari.breus@gmail.com','LARISSA BISETTO BREUS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('roberto@as.adv.br','ROBERTO AMORIM DA SILVEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('denize.mdias@gmail.com','DENIZE DE MARIA DIAS GOMES E SILVA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('ricladias@hotmail.com','CLAUDIA MARTINS DE OLIVEIRA DIAS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lferrazm@gmail.com','LUCIANA FERRAZ MENDES MELLO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luanahlopes@hotmail.com','LUANA DA CUNHA LOPES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('djanemedeirosm@gmail.com','DJANE MEDEIROS MARTINS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('danilo-public.advogado@hotmail.com','DANILO RIBEIRO CARVALHO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('jorge.mas@uol.com.br','JORGE MIGUEL ACOSTA SOARES','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('lorenagsiqueira@gmail.com','LORENA GONCALVES DE SIQUEIRA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('public.advogadofigueiredo@oi.com.br','CARLOS FIGUEIREDO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('karen@braideesouza.adv.br','KAREN ALVES DE SOUZA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('marciacristina@wasilvestre.adv.br','MARCIA CRISTINA ALVARENGA MIKAIL BASTOS','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('paiotti@perezperezpublic.advogados.adv.br','OSWALDO PAIOTTI','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fabiola_adv@hotmail.com','FABIOLA RAQUEL DA CUNHA BARBOSA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luciano.w11@hotmail.com','LUCIANO DIAS NOBREGA','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('penha@drausiorangel.com.br','MARIA DA PENHA DE ARAUJO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('fernandohenriquecardoso.adv@gmail.com','FERNANDO HENRIQUE CARDOSO','1234-PI','8699999999');
insert into public.advogado(email, nome, oab , telefone) values('luizaromeiro@yahoo.com.br','ANA LUIZA ROMEIRO GOMES','1234-PI','8699999999');